import type { Metadata } from "next";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import PolicyGenerator from "@/components/policy/PolicyGenerator";

export const metadata: Metadata = {
  title: "Free AI Policy Template for Early Childhood Services",
  description:
    "Generate a responsible AI in documentation policy for your early childhood centre or kindergarten in New Zealand or Australia. Free, no signup, ready to adopt.",
  alternates: { canonical: "/ai-policy" },
  openGraph: {
    title: "Free AI policy for early childhood services",
    description: "A responsible AI in documentation policy your service can adopt in ten minutes. Free, no signup.",
    url: "https://storyloop.space/ai-policy",
    type: "website",
  },
};

const FAQS = [
  {
    q: "Does an early childhood service need an AI policy?",
    a: "If any educator uses AI to help write documentation about children, yes. Many already do without one, which leaves both the educator and the service exposed. A short written policy sets out which tools are allowed, what information never goes into a general AI tool, and that a person reviews everything before it is shared.",
  },
  {
    q: "Can educators put children's names into ChatGPT?",
    a: "They should not use a general, publicly available AI tool for identifying information about children. In Australia the privacy regulator's guidance recommends, as best practice, not entering personal information, particularly sensitive information, into publicly available generative AI tools. In New Zealand the Privacy Commissioner's guidance asks organisations to understand how a tool handles personal information before using it.",
  },
  {
    q: "Is this policy legal advice?",
    a: "No. It is a practical starting point built from published regulator guidance. Review it against your own service's governance and obtain your own advice where needed.",
  },
  {
    q: "Is the policy generated by AI?",
    a: "No. Every sentence is written in advance and assembled from your answers, so it cannot invent a clause or a legal requirement. Nothing you type is stored or sent anywhere.",
  },
];

export default function AiPolicyPage() {
  return (
    <div className="min-h-screen bg-paper">
      <div className="print:hidden"><Navbar /></div>

      <main className="wide-shell pb-20 pt-28 sm:pt-32 print:pt-0">
        <header className="mx-auto mb-10 max-w-3xl text-center print:hidden">
          <p className="section-title mb-3">Free for any service</p>
          <h1 className="font-display text-4xl font-bold leading-tight text-ink-900 text-balance md:text-5xl">
            Your service&apos;s AI policy, written in ten minutes.
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-ink-600">
            Most early childhood services do not have one, and many educators are already using AI quietly. Answer a few
            questions and get a responsible AI in documentation policy you can adopt, share with your team and show to
            families. No signup. Nothing you type leaves your browser.
          </p>
        </header>

        <PolicyGenerator />

        <section className="mx-auto mt-16 max-w-3xl print:hidden">
          <h2 className="font-display text-2xl font-bold text-ink-900">Questions directors ask</h2>
          <div className="mt-5 space-y-5">
            {FAQS.map((faq) => (
              <div key={faq.q}>
                <h3 className="font-semibold text-ink-900">{faq.q}</h3>
                <p className="mt-1.5 leading-relaxed text-ink-600">{faq.a}</p>
              </div>
            ))}
          </div>

          <div className="mt-10 rounded-2xl border border-clay-100 bg-cream-50 p-5 text-sm leading-relaxed text-ink-600">
            <p className="font-semibold text-ink-900">Built from published guidance</p>
            <ul className="mt-2 space-y-1.5">
              <li>
                New Zealand:{" "}
                <a className="text-clay-700 underline underline-offset-2" href="https://www.privacy.org.nz/resources-and-learning/a-z-topics/ai/" target="_blank" rel="noopener noreferrer">
                  Office of the Privacy Commissioner, Artificial Intelligence and the Information Privacy Principles
                </a>{" "}
                (2023), under the Privacy Act 2020.
              </li>
              <li>
                Australia:{" "}
                <a className="text-clay-700 underline underline-offset-2" href="https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products" target="_blank" rel="noopener noreferrer">
                  OAIC, Guidance on privacy and the use of commercially available AI products
                </a>{" "}
                (2024), under the Privacy Act 1988.
              </li>
            </ul>
            <p className="mt-3 text-xs text-ink-500">Reviewed 17 September 2026 · Written by Leo, who builds StoryLoop, in Ōtautahi Christchurch</p>
          </div>
        </section>
      </main>

      <div className="print:hidden"><Footer /></div>
    </div>
  );
}
