// GENERATED by scripts/story-eval/export_examples.py. The numbers on /accuracy,
// from the story evaluation run of 2026-09-23. Do not edit by hand.

export const ACCURACY_REPORT = {
  "date": "2026-09-23",
  "notes": 24,
  "drafts": 48,
  "wordsInChildMouth": 0,
  "frameworkMixups": 0,
  "missingSections": 1,
  "fidelity": 8.77,
  "usefulness": 8.98,
  "readsNaturally": 8.94,
  "interpretationsAsFact": 67,
  "feelingsAsFact": 8,
  "medianWords": 338.5,
  "medianSeconds": 16.3,
  "byAge": [
    {
      "age": "Under 1",
      "drafts": 4,
      "fidelity": 8.0
    },
    {
      "age": "1 to 2 years",
      "drafts": 6,
      "fidelity": 8.8
    },
    {
      "age": "2 to 3 years",
      "drafts": 6,
      "fidelity": 9.2
    },
    {
      "age": "3 to 4 years",
      "drafts": 14,
      "fidelity": 8.6
    },
    {
      "age": "4 to 5 years",
      "drafts": 18,
      "fidelity": 8.9
    }
  ],
  "reviewerSamples": [
    "kept working out how to get close enough",
    "heard or felt the result",
    "babbling while shaking it",
    "waited for the fun part"
  ],
  "cases": [
    {
      "age": "Under 1",
      "framework": "NZ",
      "tests": "Babbling only. No words, no feelings named. Watch for invented pride or invented speech."
    },
    {
      "age": "Under 1",
      "framework": "AU",
      "tests": "A count is given loosely (5 or 6). Any other number is invented."
    },
    {
      "age": "1 to 2 years",
      "framework": "NZ",
      "tests": "Exactly one quote: more sand."
    },
    {
      "age": "1 to 2 years",
      "framework": "AU",
      "tests": "She did not speak. Any quote is invented."
    },
    {
      "age": "2 to 3 years",
      "framework": "NZ",
      "tests": "Quote: help me. She did not say anything else."
    },
    {
      "age": "2 to 3 years",
      "framework": "AU",
      "tests": "Lower-case name, sloppy punctuation. Quote: green. Another child: Mia."
    },
    {
      "age": "3 to 4 years",
      "framework": "AU",
      "tests": "No quote. No feelings named. Classic place models invent 'I did it by myself' or pride."
    },
    {
      "age": "3 to 4 years",
      "framework": "AU",
      "tests": "The homepage demo note. One quote."
    },
    {
      "age": "3 to 4 years",
      "framework": "NZ",
      "tests": "Educator name given. Te reo waiata title. He sang, no quote."
    },
    {
      "age": "3 to 4 years",
      "framework": "AU",
      "tests": "Physical conflict, must be framed safely. Number: 3 minutes."
    },
    {
      "age": "4 to 5 years",
      "framework": "NZ",
      "tests": "Two quotes. Another child Hemi. Number 12."
    },
    {
      "age": "4 to 5 years",
      "framework": "AU",
      "tests": "Sparse. Asked a question, but her exact words are not given, so no quote."
    },
    {
      "age": "4 to 5 years",
      "framework": "NZ",
      "tests": "Quote: that will be five dollars. Another child Ana."
    },
    {
      "age": "4 to 5 years",
      "framework": "AU",
      "tests": "Sensitive family detail should be raised by the privacy check. Quote given."
    },
    {
      "age": "4 to 5 years",
      "framework": "AU",
      "tests": "Very sparse. Anything beyond puzzle and finishing it is invented."
    },
    {
      "age": "3 to 4 years",
      "framework": "NZ",
      "tests": "Feeling stated by the child (scared). Quote given."
    },
    {
      "age": "2 to 3 years",
      "framework": "AU",
      "tests": "Book title. Number 10 minutes."
    },
    {
      "age": "4 to 5 years",
      "framework": "NZ",
      "tests": "Three children. Quote: password please. Sam said banana."
    },
    {
      "age": "1 to 2 years",
      "framework": "AU",
      "tests": "Quote: all gone."
    },
    {
      "age": "4 to 5 years",
      "framework": "AU",
      "tests": "Numbers 8, 2, ten. Quote given."
    },
    {
      "age": "3 to 4 years",
      "framework": "NZ",
      "tests": "Family detail (baby brother, name Rafi). Reported speech, not a direct quote."
    },
    {
      "age": "4 to 5 years",
      "framework": "AU",
      "tests": "Long, rich note. Two quotes. Numbers 40, two, third."
    },
    {
      "age": "4 to 5 years",
      "framework": "NZ",
      "tests": "Single-word quote: pulley."
    },
    {
      "age": "3 to 4 years",
      "framework": "AU",
      "tests": "No child name given. The story must not invent one."
    }
  ]
} as const;
